import Head from "next/head";
import { AuthContext } from "../components/Auth";
import firebase from "../utils/Firebase";

import React, { useContext, useEffect, useState } from "react";
import {
  getDatabseItems,
  setDatabseItems,
} from "../domain/debris/hook/DatabaseHandler";
import MainLayout from "../components/MainLayout";
import Calendar from "react-calendar";
import "react-calendar/dist/Calendar.css";
import { Container, Heading } from "@chakra-ui/react";
import { debriEntity } from "../domain/debris/hook/Types";
import { Converter } from "../domain/debris/hook/Converter";
import { useToast } from "@chakra-ui/react";

export default function Home({}) {
  const { currentUser } = useContext(AuthContext);
  useEffect(() => {}, [currentUser]);
  const logout = () => {
    firebase
      .auth()
      .signOut()
      .then(function () {
        // Sign-out successful.
      })
      .catch(function (error) {
        // An error happened.
      });
  };
  return (
    <div>
      <Head>
        <title>TINPANI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <Container fluid className="column">
            <Heading as="h2" mb="2">
              index
            </Heading>
            {/* <button onClick={logout}>googleでログアウト</button> */}
          </Container>
        </MainLayout>
      </main>
    </div>
  );
}
