import Head from "next/head";
import useSWR from "swr";
import { useState } from "react";

export default function Home() {
  async function fetcher(url: string): Promise<boolean | null> {
    const response = await fetch(url);
    return response.json();
  }
  async function Fuck(apiData: any) {
    const values: [] = await apiData.map((data: any) => {
      return {
        id: data.id,
        title: data.title,
        url: data.url,
      };
    });
    return values;
  }
  const { data, error } = useSWR(
    "https://qiita.com/api/v2/users/ozwld51/stocks?page=1&per_page=2",
    fetcher
  );

  if (error) return <div>failed to load</div>;
  if (!data) return <div>ロード中</div>;
  console.log("dammmmm", Fuck(data));

  if (data)
    return (
      <div>
        <Head>
          <title>Qiita Test</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          {/* <QiitaBody data={text} /> */}
          <p>テストページ</p>
          {/* {data.map((todo) => {
              return <div>a</div>;
            })} */}
        </main>
      </div>
    );
}
