import Head from "next/head";
import Router from "next/router";

import ModalChildrenPage from "../../domain/todo/components/ModalChildrenPage";
import MainLayout from "../../components/MainLayout";
import TodoBody from "../../domain/todo/components/TodoBody";

import {
  Modal,
  ModalOverlay,
  ModalContent,
  ModalHeader,
  ModalFooter,
  ModalBody,
  ModalCloseButton,
  useDisclosure,
} from "@chakra-ui/react";
import {
  Container,
  Heading,
  Button,
  Box,
  Grid,
  GridItem,
  Flex,
  Center,
  Input,
  Textarea,
} from "@chakra-ui/react";
// export async function getServerSideProps({ query }) {
//   console.log(query.item);
//   if (query.item) {
//     return {
//       props: { item: query.item },
//     };
//   } else {
//     return {
//       //   redirect: {
//       //     destination: "/todo",
//       //     statusCode: 307,
//       //   },
//     };
//   }
// }

export default function Home(props: any) {
  const { isOpen, onOpen, onClose } = useDisclosure();
  if (props.item) {
    onOpen;
  }
  return (
    <div>
      <Head>
        <title>PO - TINPANI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <Heading as="h2" mb="2">
            TODO
          </Heading>
          <div>
            <TodoBody value="tesss" />
          </div>

          <div>
            <Button onClick={onOpen}>Open Modal</Button>
            <Modal isOpen={isOpen} onClose={onClose} scrollBehavior="outside">
              <ModalOverlay />
              <ModalChildrenPage itemKey={props.item} onClose={onClose} />
            </Modal>
          </div>
        </MainLayout>
      </main>
    </div>
  );
}
